### ISSUE TITLE
[Feature] continuous gesture support

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#10]
Currently, multitouch gestures work just fine for discrete motions like `scroller:movefocus` 

Support for something like this could be done in, e.g. [fusuma](https://github.com/iberianpig/fusuma), for continuous motion:

```
swipe:
  3:
    up:
      update:
        command: 'hyprctl dispatch scroller:scroll u'
    down:
      update:
        command: 'hyprctl dispatch scroller:scroll d'
```

The effect would be similar to scrolling on a page but through window rows/cols
